/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_get_move_score: (a: number) => number;
export const __wbg_get_move_x: (a: number) => number;
export const __wbg_get_move_y: (a: number) => number;
export const __wbg_get_move_z: (a: number) => number;
export const __wbg_get_searchresult_depth: (a: number) => number;
export const __wbg_move_free: (a: number, b: number) => void;
export const __wbg_searchresult_free: (a: number, b: number) => void;
export const __wbg_set_move_score: (a: number, b: number) => void;
export const __wbg_set_move_x: (a: number, b: number) => void;
export const __wbg_set_move_y: (a: number, b: number) => void;
export const __wbg_set_move_z: (a: number, b: number) => void;
export const __wbg_set_searchresult_depth: (a: number, b: number) => void;
export const get_best_move: (a: bigint, b: bigint, c: number, d: number, e: any) => any;
export const __wbg_set_searchresult_score: (a: number, b: number) => void;
export const clear_tt: () => void;
export const __wbg_get_searchresult_x: (a: number) => number;
export const __wbg_get_searchresult_y: (a: number) => number;
export const __wbg_get_searchresult_z: (a: number) => number;
export const __wbg_get_searchresult_score: (a: number) => number;
export const __wbg_set_searchresult_x: (a: number, b: number) => void;
export const __wbg_set_searchresult_y: (a: number, b: number) => void;
export const __wbg_set_searchresult_z: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_start: () => void;
